/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

// Important: Precache all assets generated by the build process
// This __WB_MANIFEST variable will be replaced by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// --- RUNTIME CACHING ---

// 1. Google Fonts (Stylesheets)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// 2. Google Fonts (Font Files)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
);

// 3. Mushaf Images (Quran Pages)
// Source: android.quran.com
registerRoute(
  ({ url }) => url.origin === 'https://android.quran.com',
  new CacheFirst({
    cacheName: 'quran-mushaf-images-v1', // Must match the cache name in mushafService.ts
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 1000,
      }),
    ],
  })
);

// 4. Quran Cloud API (Quran Text, Translation)
registerRoute(
  ({ url }) => url.origin === 'https://api.alquran.cloud',
  new StaleWhileRevalidate({
    cacheName: 'api-quran-cloud',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
        maxEntries: 100,
      }),
    ],
  })
);

// 5. Quran.com API (Word by Word)
registerRoute(
  ({ url }) => url.origin === 'https://api.quran.com',
  new StaleWhileRevalidate({
    cacheName: 'api-quran-com-v4',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
        maxEntries: 50,
      }),
    ],
  })
);

// --- NAVIGATION FALLBACK ---

// Support for Single Page Application (SPA)
// Arahkan semua navigasi ke index.html saat offline
registerRoute(
  new NavigationRoute((params) => {
    const { event } = (params as unknown) as { event: FetchEvent };
    return caches.match('/index.html').then((response) => {
      return response || fetch(event.request);
    });
  })
);

// --- APP NOTIFICATION / UPDATES ---

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
