/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

// 1. Precache all assets generated by Vite build process
precacheAndRoute(self.__WB_MANIFEST || []);

// 2. Cleanup outdated caches automatically
cleanupOutdatedCaches();

// --- CRITICAL ASSETS LIST FOR OFFLINE RESILIENCE ---
const CORE_OFFLINE_LIBRARIES = [
  'https://cdn.tailwindcss.com',
  'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&family=Lora:ital,wght@0,400;0,500;1,400&display=swap',
  '/logo.svg',
  '/icon.png',
  '/quran-json/quran.json',
  '/quran-json/verse-meta.json'
];

const CORE_CACHE_NAME = 'app-core-libs-v2';

/**
 * Pre-warms and caches critical libraries and assets during installation.
 * Ensures the app has all required styling, fonts, and data offline on first visit.
 */
async function prewarmCoreAssets(): Promise<void> {
  try {
    const cache = await caches.open(CORE_CACHE_NAME);
    await Promise.allSettled(
      CORE_OFFLINE_LIBRARIES.map(async (url) => {
        try {
          const cached = await cache.match(url);
          if (!cached) {
            const response = await fetch(url, { mode: url.startsWith('http') ? 'cors' : 'same-origin' })
              .catch(() => fetch(url, { mode: 'no-cors' }));
            if (response && (response.status === 200 || response.type === 'opaque')) {
              await cache.put(url, response);
            }
          }
        } catch (err) {
          console.warn('[SW Prewarm] Failed caching asset:', url, err);
        }
      })
    );
  } catch (error) {
    console.error('[SW Prewarm] Error prewarming core assets:', error);
  }
}

/**
 * Self-healing / Verification utility:
 * Checks for missing critical assets and re-downloads them if incomplete.
 */
async function verifyAndDownloadMissingAssets(client?: Client | null): Promise<void> {
  const cache = await caches.open(CORE_CACHE_NAME);
  let missingCount = 0;
  let downloadedCount = 0;

  for (const url of CORE_OFFLINE_LIBRARIES) {
    try {
      const match = await cache.match(url);
      if (!match) {
        missingCount++;
        const response = await fetch(url, { mode: url.startsWith('http') ? 'cors' : 'same-origin' })
          .catch(() => fetch(url, { mode: 'no-cors' }));
        if (response && (response.status === 200 || response.type === 'opaque')) {
          await cache.put(url, response);
          downloadedCount++;
        }
      }
    } catch (err) {
      console.warn('[SW Self-Healing] Could not fetch missing asset:', url, err);
    }
  }

  // Also ensure /index.html is stored in cache for offline SPA navigation
  try {
    const indexMatch = await caches.match('/index.html');
    if (!indexMatch) {
      const idxRes = await fetch('/index.html');
      if (idxRes.ok) {
        await cache.put('/index.html', idxRes);
        downloadedCount++;
      }
    }
  } catch {
    // ignore offline fetch failure
  }

  if (client && 'postMessage' in client) {
    client.postMessage({
      type: 'OFFLINE_ASSETS_SYNC_RESULT',
      missing: missingCount,
      downloaded: downloadedCount,
      timestamp: Date.now()
    });
  }
}

// Immediately take control upon install & activate
self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(prewarmCoreAssets());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      self.clients.claim(),
      prewarmCoreAssets()
    ])
  );
});

// --- RUNTIME CACHING STRATEGIES ---

// 1. Tailwind CSS CDN (Core UI Library)
registerRoute(
  ({ url }) => url.origin === 'https://cdn.tailwindcss.com',
  new CacheFirst({
    cacheName: CORE_CACHE_NAME,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 10,
      }),
    ],
  })
);

// 2. ESM.sh External Library CDN
registerRoute(
  ({ url }) => url.origin === 'https://esm.sh',
  new CacheFirst({
    cacheName: 'app-esm-libs-v2',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 60,
      }),
    ],
  })
);

// 3. Google Fonts (Stylesheets)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// 4. Google Fonts (Font Files - woff2/ttf)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 40,
      }),
    ],
  })
);

// 5. Local Quran Data & QUL Assets (/quran-json/** & /qul/**)
registerRoute(
  ({ url }) => url.pathname.startsWith('/quran-json/') || url.pathname.startsWith('/qul/'),
  new CacheFirst({
    cacheName: 'quran-offline-data-v2',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 350,
      }),
    ],
  })
);

// 6. Mushaf Images (Quran Pages from android.quran.com)
registerRoute(
  ({ url }) => url.origin === 'https://android.quran.com',
  new CacheFirst({
    cacheName: 'quran-mushaf-images-v2',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 1000,
      }),
    ],
  })
);

// 7. Quran Cloud API (Quran Text & Translations)
registerRoute(
  ({ url }) => url.origin === 'https://api.alquran.cloud',
  new StaleWhileRevalidate({
    cacheName: 'api-quran-cloud',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
        maxEntries: 120,
      }),
    ],
  })
);

// 8. Quran.com API (Word by Word & Metadata)
registerRoute(
  ({ url }) => url.origin === 'https://api.quran.com',
  new StaleWhileRevalidate({
    cacheName: 'api-quran-com-v4',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
        maxEntries: 60,
      }),
    ],
  })
);

// --- NAVIGATION FALLBACK FOR SINGLE PAGE APPLICATION (SPA) ---
// Route all navigation requests to index.html with cache fallback when offline
registerRoute(
  new NavigationRoute(async (params) => {
    try {
      // First try to serve cached index.html
      const cached = await caches.match('/index.html');
      if (cached) return cached;

      // Otherwise attempt network
      const { event } = (params as unknown) as { event: FetchEvent };
      return await fetch(event.request);
    } catch {
      // Offline fallback: try finding any cached index.html
      const fallback = await caches.match('/index.html') || await caches.match('index.html');
      if (fallback) return fallback;
      return new Response('Offline - Silakan periksa koneksi Anda', {
        headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        status: 503
      });
    }
  })
);

// --- SERVICE WORKER MESSAGING & SELF-HEALING HOOKS ---
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  if (event.data && (event.data.type === 'VERIFY_AND_SYNC_OFFLINE' || event.data.type === 'CHECK_OFFLINE_CACHE')) {
    event.waitUntil(verifyAndDownloadMissingAssets(event.source as Client));
  }
});
