
export interface AsmaulHusna {
    index: number;
    latin: string;
    arabic: string;
    translation_id: string;
    translation_en: string;
}

export const ASMAUL_HUSNA: AsmaulHusna[] = [
    { index: 1, latin: "Ar Rahman", arabic: "الرَّة\u0652م\u064eن", translation_id: "Yang Maha Pengasih", translation_en: "The Beneficent" },
    { index: 2, latin: "Ar Rahim", arabic: "الرَّح\u0650يم", translation_id: "Yang Maha Penyayang", translation_en: "The Merciful" },
    { index: 3, latin: "Al Malik", arabic: "الْم\u064eل\u0650ك", translation_id: "Yang Maha Merajai", translation_en: "The King" },
    { index: 4, latin: "Al Quddus", arabic: "الْق\u064fدُّوس", translation_id: "Yang Maha Suci", translation_en: "The Most Holy" },
    { index: 5, latin: "As Salam", arabic: "السَّل\u0627م", translation_id: "Yang Maha Memberi Kesejahteraan", translation_en: "The Source of Peace" },
    { index: 6, latin: "Al Mu'min", arabic: "الْم\u064fؤ\u0652م\u0650ن", translation_id: "Yang Maha Memberi Keamanan", translation_en: "The Guardian of Faith" },
    { index: 7, latin: "Al Muhaimin", arabic: "الْم\u064fه\u064eي\u0652م\u0650ن", translation_id: "Yang Maha Pemelihara", translation_en: "The Protector" },
    { index: 8, latin: "Al Aziz", arabic: "الْع\u064eز\u0650يز", translation_id: "Yang Maha Perkasa", translation_en: "The Mighty" },
    { index: 9, latin: "Al Jabbar", arabic: "الْج\u064eبَّار", translation_id: "Yang Maha Memiliki Mutlak Kegagahan", translation_en: "The Compeller" },
    { index: 10, latin: "Al Mutakabbir", arabic: "الْم\u064fت\u064eك\u064eبِّر", translation_id: "Yang Maha Megah", translation_en: "The Majestic" },
    { index: 11, latin: "Al Khaliq", arabic: "الْخ\u0627ل\u0650ق", translation_id: "Yang Maha Pencipta", translation_en: "The Creator" },
    { index: 12, latin: "Al Baari", arabic: "الْب\u0627ر\u0650ئ", translation_id: "Yang Maha Melepaskan", translation_en: "The Evolver" },
    { index: 13, latin: "Al Musawwir", arabic: "الْم\u064fص\u064eوِّر", translation_id: "Yang Maha Membentuk Rupa", translation_en: "The Fashioner" },
    { index: 14, latin: "Al Ghaffar", arabic: "الْغ\u064eفَّار", translation_id: "Yang Maha Pengampun", translation_en: "The Forgiver" },
    { index: 15, latin: "Al Qahhar", arabic: "الْق\u064eهَّار", translation_id: "Yang Maha Memaksa", translation_en: "The Subduer" },
    { index: 16, latin: "Al Wahhab", arabic: "الْو\u064eهَّاب", translation_id: "Yang Maha Pemberi Karunia", translation_en: "The Bestower" },
    { index: 17, latin: "Ar Razzaq", arabic: "الرَّزَّاق", translation_id: "Yang Maha Pemberi Rezeki", translation_en: "The Provider" },
    { index: 18, latin: "Al Fattah", arabic: "الْف\u064eتَّاح", translation_id: "Yang Maha Pembuka Rahmat", translation_en: "The Opener" },
    { index: 19, latin: "Al 'Alim", arabic: "الْع\u064eل\u0650يم", translation_id: "Yang Maha Mengetahui", translation_en: "The All-Knowing" },
    { index: 20, latin: "Al Qabidh", arabic: "الْق\u0627ب\u0650ض", translation_id: "Yang Maha Menyempitkan", translation_en: "The Constrictor" },
    { index: 21, latin: "Al Basit", arabic: "الْب\u0627س\u0650ط", translation_id: "Yang Maha Melapangkan", translation_en: "The Expander" },
    { index: 22, latin: "Al Khafid", arabic: "الْخ\u0627ف\u0650ض", translation_id: "Yang Maha Merendahkan", translation_en: "The Abaser" },
    { index: 23, latin: "Ar Rafi'", arabic: "الرَّاف\u0650ع", translation_id: "Yang Maha Meninggikan", translation_en: "The Exalter" },
    { index: 24, latin: "Al Mu'izz", arabic: "الْم\u064fع\u0650زّ", translation_id: "Yang Maha Memuliakan", translation_en: "The Bestower of Honors" },
    { index: 25, latin: "Al Mudzil", arabic: "الْم\u064fذ\u0650لّ", translation_id: "Yang Maha Menghinakan", translation_en: "The Dishonorer" },
    { index: 26, latin: "As Sami'", arabic: "السَّم\u0650يع", translation_id: "Yang Maha Mendengar", translation_en: "The All-Hearing" },
    { index: 27, latin: "Al Bashir", arabic: "الْب\u064eص\u0650ير", translation_id: "Yang Maha Melihat", translation_en: "The All-Seeing" },
    { index: 28, latin: "Al Hakam", arabic: "الْح\u064eك\u064eم", translation_id: "Yang Maha Menetapkan", translation_en: "The Judge" },
    { index: 29, latin: "Al 'Adl", arabic: "الْع\u064eد\u0652ل", translation_id: "Yang Maha Adil", translation_en: "The Just" },
    { index: 30, latin: "Al Latif", arabic: "اللَّط\u0650يف", translation_id: "Yang Maha Lembut", translation_en: "The Subtle One" },
    { index: 31, latin: "Al Khabir", arabic: "الْخ\u064eب\u0650ير", translation_id: "Yang Maha Mengenal", translation_en: "The All-Aware" },
    { index: 32, latin: "Al Halim", arabic: "الْح\u064eل\u0650يم", translation_id: "Yang Maha Penyantun", translation_en: "The Forbearing" },
    { index: 33, latin: "Al 'Azhim", arabic: "الْع\u064eظ\u0650يم", translation_id: "Yang Maha Agung", translation_en: "The Magnificent" },
    { index: 34, latin: "Al Ghafur", arabic: "الْغ\u064eف\u064fور", translation_id: "Yang Maha Memberi Pengampunan", translation_en: "The Forgiver" },
    { index: 35, latin: "As Syakur", arabic: "الشَّك\u064fور", translation_id: "Yang Maha Pembalas Budi", translation_en: "The Appreciative" },
    { index: 36, latin: "Al 'Ali", arabic: "الْع\u064eل\u0650يّ", translation_id: "Yang Maha Tinggi", translation_en: "The Highest" },
    { index: 37, latin: "Al Kabir", arabic: "الْك\u064eب\u0650ير", translation_id: "Yang Maha Besar", translation_en: "The Greatest" },
    { index: 38, latin: "Al Hafizh", arabic: "الْح\u064eف\u0650يظ", translation_id: "Yang Maha Memelihara", translation_en: "The Preserver" },
    { index: 39, latin: "Al Muqit", arabic: "الْم\u064fق\u0650يت", translation_id: "Yang Maha Pemberi Kecukupan", translation_en: "The Nourisher" },
    { index: 40, latin: "Al Hasib", arabic: "الْح\u064eس\u0650يب", translation_id: "Yang Maha Membuat Perhitungan", translation_en: "The Accounter" },
    { index: 41, latin: "Al Jalil", arabic: "الْج\u064eل\u0650يل", translation_id: "Yang Maha Luhur", translation_en: "The Mighty" },
    { index: 42, latin: "Al Karim", arabic: "الْك\u064eر\u0650يم", translation_id: "Yang Maha Pemurah", translation_en: "The Generous" },
    { index: 43, latin: "Ar Raqib", arabic: "الرَّق\u0650يب", translation_id: "Yang Maha Mengawasi", translation_en: "The Watchful" },
    { index: 44, latin: "Al Mujib", arabic: "الْم\u064fج\u0650يب", translation_id: "Yang Maha Mengabulkan", translation_en: "The Responder" },
    { index: 45, latin: "Al Wasi'", arabic: "الْو\u0627س\u0650ع", translation_id: "Yang Maha Luas", translation_en: "The All-Encompassing" },
    { index: 46, latin: "Al Hakim", arabic: "الْح\u064eك\u0650يم", translation_id: "Yang Maha Bijaksana", translation_en: "The Wise" },
    { index: 47, latin: "Al Wadud", arabic: "الْو\u064eد\u064fود", translation_id: "Yang Maha Mengasihi", translation_en: "The Loving" },
    { index: 48, latin: "Al Majid", arabic: "الْم\u064eج\u0650يد", translation_id: "Yang Maha Mulia", translation_en: "The Glorious" },
    { index: 49, latin: "Al Ba'ith", arabic: "الْب\u0627ع\u0650ث", translation_id: "Yang Maha Membangkitkan", translation_en: "The Resurrecter" },
    { index: 50, latin: "As Shahid", arabic: "الشَّه\u0650يد", translation_id: "Yang Maha Menyaksikan", translation_en: "The Witness" },
    { index: 51, latin: "Al Haqq", arabic: "الْح\u064eقّ", translation_id: "Yang Maha Benar", translation_en: "The Truth" },
    { index: 52, latin: "Al Wakil", arabic: "الْو\u064eك\u0650يل", translation_id: "Yang Maha Memelihara", translation_en: "The Trustee" },
    { index: 53, latin: "Al Qawiyy", arabic: "الْق\u064eو\u0650يّ", translation_id: "Yang Maha Kuat", translation_en: "The Strong" },
    { index: 54, latin: "Al Matin", arabic: "الْم\u064eت\u0650ين", translation_id: "Yang Maha Kokoh", translation_en: "The Firm" },
    { index: 55, latin: "Al Waliyy", arabic: "الْو\u064eل\u0650يّ", translation_id: "Yang Maha Melindungi", translation_en: "The Friend" },
    { index: 56, latin: "Al Hamid", arabic: "الْح\u064eم\u0650يد", translation_id: "Yang Maha Terpuji", translation_en: "The Praiseworthy" },
    { index: 57, latin: "Al Muhshi", arabic: "الْم\u064fح\u0652ص\u0650ي", translation_id: "Yang Maha Mengalkulasi", translation_en: "The Counter" },
    { index: 58, latin: "Al Mubdi", arabic: "الْم\u064fب\u0652د\u0650ئ", translation_id: "Yang Maha Memulai", translation_en: "The Originator" },
    { index: 59, latin: "Al Mu'id", arabic: "الْم\u064fع\u0650يد", translation_id: "Yang Maha Mengembalikan Kehidupan", translation_en: "The Restorer" },
    { index: 60, latin: "Al Muhyi", arabic: "الْم\u064fح\u0652ي\u0650ي", translation_id: "Yang Maha Menghidupkan", translation_en: "The Giver of Life" },
    { index: 61, latin: "Al Mumit", arabic: "الْم\u064fم\u0650يت", translation_id: "Yang Maha Mematikan", translation_en: "The Taker of Life" },
    { index: 62, latin: "Al Hayyu", arabic: "الْح\u064eي", translation_id: "Yang Maha Hidup", translation_en: "The Living" },
    { index: 63, latin: "Al Qayyum", arabic: "الْق\u064eيُّوم", translation_id: "Yang Maha Mandiri", translation_en: "The Subsisting" },
    { index: 64, latin: "Al Wajid", arabic: "الْو\u0627ج\u0650د", translation_id: "Yang Maha Penemu", translation_en: "The Finder" },
    { index: 65, latin: "Al Majid", arabic: "الْم\u0627ج\u0650د", translation_id: "Yang Maha Mulia", translation_en: "The Glorious" },
    { index: 66, latin: "Al Wahid", arabic: "الْو\u0627ح\u0650د", translation_id: "Yang Maha Tunggal", translation_en: "The One" },
    { index: 67, latin: "Al Ahad", arabic: "الْأَح\u064eد", translation_id: "Yang Maha Esa", translation_en: "The Unique" },
    { index: 68, latin: "As Samad", arabic: "الصَّم\u064eد", translation_id: "Yang Maha Dibutuhkan", translation_en: "The Eternal" },
    { index: 69, latin: "Al Qadir", arabic: "الْق\u0627د\u0650ر", translation_id: "Yang Maha Menentukan", translation_en: "The Able" },
    { index: 70, latin: "Al Muqtadir", arabic: "الْم\u064fق\u0652ت\u064eد\u0650ر", translation_id: "Yang Maha Berkuasa", translation_en: "The Powerful" },
    { index: 71, latin: "Al Muqaddim", arabic: "الْم\u064fق\u064eدِّم", translation_id: "Yang Maha Mendahulukan", translation_en: "The Expediter" },
    { index: 72, latin: "Al Mu'akhkhir", arabic: "الْم\u064fؤ\u064eخِّر", translation_id: "Yang Maha Mengakhirkan", translation_en: "The Delayer" },
    { index: 73, latin: "Al Awwal", arabic: "الْأَوَّل", translation_id: "Yang Maha Awal", translation_en: "The First" },
    { index: 74, latin: "Al Akhir", arabic: "الْآخ\u0650ر", translation_id: "Yang Maha Akhir", translation_en: "The Last" },
    { index: 75, latin: "Az Zhahir", arabic: "الظَّاه\u0650ر", translation_id: "Yang Maha Nyata", translation_en: "The Manifest" },
    { index: 76, latin: "Al Batin", arabic: "الْب\u0627ط\u0650ن", translation_id: "Yang Maha Ghaib", translation_en: "The Hidden" },
    { index: 77, latin: "Al Wali", arabic: "الْو\u0627ل\u0650ي", translation_id: "Yang Maha Memerintah", translation_en: "The Governor" },
    { index: 78, latin: "Al Muta'ali", arabic: "الْم\u064fت\u064eع\u0627ل\u0650ي", translation_id: "Yang Maha Tinggi", translation_en: "The Exalted" },
    { index: 79, latin: "Al Barr", arabic: "الْب\u064eرّ", translation_id: "Yang Maha Penderma", translation_en: "The Righteous" },
    { index: 80, latin: "At Tawwab", arabic: "التَّوَّاب", translation_id: "Yang Maha Penerima Tobat", translation_en: "The Acceptor of Repentance" },
    { index: 81, latin: "Al Muntaqim", arabic: "الْم\u064fن\u0652ت\u064eق\u0650م", translation_id: "Yang Maha Pemberi Balasan", translation_en: "The Avenger" },
    { index: 82, latin: "Al 'Afuww", arabic: "الْع\u064eف\u064fوّ", translation_id: "Yang Maha Pemaaf", translation_en: "The Pardoner" },
    { index: 83, latin: "Ar Ra'uf", arabic: "الرَّؤ\u064fوف", translation_id: "Yang Maha Pengasuh", translation_en: "The Compassionate" },
    { index: 84, latin: "Malikul Mulk", arabic: "م\u0627ل\u0650ك\u064f الْم\u064fل\u0652ك", translation_id: "Yang Maha Penguasa Kerajaan", translation_en: "The Owner of Sovereignty" },
    { index: 85, latin: "Dzul Jalali wal Ikram", arabic: "ذ\u064fو الْج\u064eلال\u0650 وَالْإِك\u0652رام", translation_id: "Yang Maha Memiliki Kebesaran dan Kemuliaan", translation_en: "The Lord of Majesty and Generosity" },
    { index: 86, latin: "Al Muqsith", arabic: "الْم\u064fق\u0652س\u0650ط", translation_id: "Yang Maha Pemberi Keadilan", translation_en: "The Equitable" },
    { index: 87, latin: "Al Jami'", arabic: "الْج\u0627م\u0650ع", translation_id: "Yang Maha Mengumpulkan", translation_en: "The Gatherer" },
    { index: 88, latin: "Al Ghaniyy", arabic: "الْغ\u064eن\u0650يّ", translation_id: "Yang Maha Kaya", translation_en: "The Self-Sufficient" },
    { index: 89, latin: "Al Mughni", arabic: "الْم\u064fغ\u0652ن\u0650ي", translation_id: "Yang Maha Pemberi Kekayaan", translation_en: "The Enricher" },
    { index: 90, latin: "Al Mani'", arabic: "الْم\u0627ن\u0650ع", translation_id: "Yang Maha Mencegah", translation_en: "The Preventer" },
    { index: 91, latin: "Ad Dhaar", arabic: "الضَّار", translation_id: "Yang Maha Penimpa Kemudharatan", translation_en: "The Distresser" },
    { index: 92, latin: "An Nafi'", arabic: "النَّاف\u0650ع", translation_id: "Yang Maha Memberi Manfaat", translation_en: "The Propitious" },
    { index: 93, latin: "An Nur", arabic: "النُّور", translation_id: "Yang Maha Bercahaya", translation_en: "The Light" },
    { index: 94, latin: "Al Hadi", arabic: "الْه\u0627د\u0650ي", translation_id: "Yang Maha Pemberi Petunjuk", translation_en: "The Guide" },
    { index: 95, latin: "Al Badi'", arabic: "الْب\u064eد\u0650يع", translation_id: "Yang Maha Pencipta", translation_en: "The Incomparable" },
    { index: 96, latin: "Al Baqi", arabic: "الْب\u0627ق\u0650ي", translation_id: "Yang Maha Kekal", translation_en: "The Ever-Enduring" },
    { index: 97, latin: "Al Warits", arabic: "الْو\u0627ر\u0650ث", translation_id: "Yang Maha Pewaris", translation_en: "The Inheritor" },
    { index: 98, latin: "Ar Rashid", arabic: "الرَّش\u0650يد", translation_id: "Yang Maha Pandai", translation_en: "The Guide to the Right Path" },
    { index: 99, latin: "As Sabur", arabic: "الصَّب\u064fور", translation_id: "Yang Maha Sabar", translation_en: "The Patient" }
];
