import { Topic } from '../types';

export const TOPICS: Topic[] = [
    {
        id: 'iman',
        title: 'Iman & Aqidah',
        description: 'Ayat-ayat tentang keimanan kepada Allah, Malaikat, Kitab, Rasul, dan Hari Akhir.',
        iconName: 'Moon',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 3 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 75 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 109 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 143 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 214 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 255 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 7 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 73 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 118 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 156 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 200 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 57 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 92 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 141 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 1 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 50 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 81 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 111 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 92 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 154 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 76 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 126 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 196 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 27 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 75 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 28 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 71 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 107 },
            { surahId: 10, surahName: 'Yunus', verseId: 13 },
            { surahId: 10, surahName: 'Yunus', verseId: 96 },
            { surahId: 11, surahName: 'Hud', verseId: 40 },
            { surahId: 12, surahName: 'Yusuf', verseId: 36 },
            { surahId: 12, surahName: 'Yusuf', verseId: 111 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 35 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 79 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 10 },
            { surahId: 18, surahName: 'Al-Kahf', verseId: 2 },
            { surahId: 19, surahName: 'Maryam', verseId: 60 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 127 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 17 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 47 },
            { surahId: 24, surahName: 'An-Nur', verseId: 27 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 24 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 125 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 215 },
            { surahId: 27, surahName: 'An-Naml', verseId: 83 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 67 },
            { surahId: 29, surahName: 'Al-\'Ankabut', verseId: 27 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 30 },
            { surahId: 32, surahName: 'As-Sajdah', verseId: 15 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 36 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 70 },
            { surahId: 35, surahName: 'Fatir', verseId: 7 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 132 },
            { surahId: 40, surahName: 'Ghafir', verseId: 10 },
            { surahId: 40, surahName: 'Ghafir', verseId: 65 },
            { surahId: 42, surahName: 'Asy-Syura', verseId: 36 },
            { surahId: 44, surahName: 'Ad-Dukhan', verseId: 55 },
            { surahId: 46, surahName: 'Al-Ahqaf', verseId: 15 },
            { surahId: 48, surahName: 'Al-Fath', verseId: 5 },
            { surahId: 49, surahName: 'Al-Hujurat', verseId: 7 },
            { surahId: 52, surahName: 'Ath-Thur', verseId: 33 },
            { surahId: 58, surahName: 'Al-Mujadilah', verseId: 9 },
            { surahId: 60, surahName: 'Al-Mumtahanah', verseId: 2 },
            { surahId: 62, surahName: 'Al-Jumu\'ah', verseId: 9 },
        ]
    },
    {
        id: 'sabar',
        title: 'Kesabaran',
        description: 'Petunjuk Al-Quran tentang bersabar menghadapi ujian hidup dan ketetapan Allah.',
        iconName: 'HeartHandshake',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 45 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 153 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 155 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 177 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 249 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 250 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 286 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 17 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 120 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 125 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 142 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 146 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 186 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 200 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 34 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 152 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 164 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 42 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 87 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 126 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 128 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 137 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 46 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 65 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 66 },
            { surahId: 10, surahName: 'Yunus', verseId: 109 },
            { surahId: 11, surahName: 'Hud', verseId: 11 },
            { surahId: 11, surahName: 'Hud', verseId: 49 },
            { surahId: 11, surahName: 'Hud', verseId: 115 },
            { surahId: 12, surahName: 'Yusuf', verseId: 18 },
            { surahId: 12, surahName: 'Yusuf', verseId: 83 },
            { surahId: 12, surahName: 'Yusuf', verseId: 90 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 22 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 23 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 24 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 5 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 12 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 21 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 42 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 96 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 110 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 126 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 127 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 15 },
            { surahId: 18, surahName: 'Al-Kahf', verseId: 82 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 130 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 85 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 34 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 35 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 62 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 111 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 20 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 75 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 54 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 80 },
            { surahId: 29, surahName: 'Al-\'Ankabut', verseId: 59 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 60 },
            { surahId: 31, surahName: 'Luqman', verseId: 17 },
            { surahId: 31, surahName: 'Luqman', verseId: 31 },
            { surahId: 32, surahName: 'As-Sajdah', verseId: 24 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 35 },
            { surahId: 34, surahName: 'Saba\'', verseId: 19 },
            { surahId: 35, surahName: 'Fatir', verseId: 18 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 102 },
            { surahId: 38, surahName: 'Sad', verseId: 17 },
        ]
    },
    {
        id: 'keluarga',
        title: 'Keluarga & Orang Tua',
        description: 'Hukum pernikahan, mendidik anak, dan berbakti pada kedua orang tua.',
        iconName: 'Users',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 40 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 44 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 48 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 52 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 56 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 60 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 64 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 68 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 72 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 76 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 80 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 84 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 88 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 92 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 96 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 100 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 116 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 187 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 221 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 229 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 233 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 237 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 241 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 49 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 2 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 7 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 12 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 22 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 27 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 75 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 129 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 5 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 72 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 137 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 26 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 105 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 172 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 55 },
            { surahId: 10, surahName: 'Yunus', verseId: 85 },
            { surahId: 11, surahName: 'Hud', verseId: 72 },
            { surahId: 12, surahName: 'Yusuf', verseId: 25 },
            { surahId: 12, surahName: 'Yusuf', verseId: 29 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 4 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 34 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 104 },
            { surahId: 18, surahName: 'Al-Kahf', verseId: 46 },
            { surahId: 19, surahName: 'Maryam', verseId: 32 },
            { surahId: 19, surahName: 'Maryam', verseId: 88 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 80 },
            { surahId: 24, surahName: 'An-Nur', verseId: 2 },
            { surahId: 24, surahName: 'An-Nur', verseId: 7 },
            { surahId: 24, surahName: 'An-Nur', verseId: 23 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 2 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 18 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 197 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 23 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 27 },
            { surahId: 31, surahName: 'Luqman', verseId: 14 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 33 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 50 },
            { surahId: 34, surahName: 'Saba\'', verseId: 37 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 4 },
            { surahId: 42, surahName: 'Asy-Syura', verseId: 49 },
            { surahId: 43, surahName: 'Az-Zukhruf', verseId: 81 },
            { surahId: 46, surahName: 'Al-Ahqaf', verseId: 15 },
        ]
    },
    {
        id: 'doa',
        title: 'Kumpulan Doa',
        description: 'Doa-doa para Nabi dan orang saleh yang diabadikan dalam Al-Quran.',
        iconName: 'Sparkles',
        references: [
            { surahId: 1, surahName: 'Al-Fatihah', verseId: 6 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 45 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 125 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 128 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 153 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 201 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 250 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 286 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 16 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 39 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 147 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 192 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 43 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 77 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 103 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 6 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 55 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 91 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 72 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 23 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 89 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 151 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 206 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 40 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 18 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 71 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 103 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 129 },
            { surahId: 10, surahName: 'Yunus', verseId: 87 },
            { surahId: 11, surahName: 'Hud', verseId: 114 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 22 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 35 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 38 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 41 },
            { surahId: 15, surahName: 'Al-Hijr', verseId: 99 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 24 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 80 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 111 },
            { surahId: 19, surahName: 'Maryam', verseId: 10 },
            { surahId: 19, surahName: 'Maryam', verseId: 59 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 26 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 29 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 130 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 83 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 18 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 41 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 2 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 29 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 98 },
            { surahId: 24, surahName: 'An-Nur', verseId: 36 },
            { surahId: 24, surahName: 'An-Nur', verseId: 56 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 64 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 74 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 80 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 83 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 87 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 118 },
            { surahId: 27, surahName: 'An-Naml', verseId: 3 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 21 },
            { surahId: 29, surahName: 'Al-\'Ankabut', verseId: 45 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 31 },
            { surahId: 32, surahName: 'As-Sajdah', verseId: 15 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 43 },
            { surahId: 35, surahName: 'Fatir', verseId: 29 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 180 },
            { surahId: 38, surahName: 'Sad', verseId: 18 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 46 },
            { surahId: 40, surahName: 'Ghafir', verseId: 9 },
            { surahId: 42, surahName: 'Asy-Syura', verseId: 38 },
            { surahId: 44, surahName: 'Ad-Dukhan', verseId: 12 },
        ]
    },
    {
        id: 'rezeki',
        title: 'Rezeki & Sedekah',
        description: 'Ayat tentang mencari nafkah halal, sedekah, infak, dan keberkahan harta.',
        iconName: 'Coins',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 43 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 110 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 177 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 196 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 215 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 219 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 261 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 262 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 263 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 264 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 265 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 271 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 272 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 273 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 274 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 275 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 276 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 277 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 278 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 92 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 130 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 134 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 180 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 37 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 38 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 39 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 92 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 114 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 161 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 12 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 45 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 55 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 41 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 5 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 18 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 58 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 60 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 71 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 75 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 76 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 79 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 103 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 121 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 71 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 73 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 36 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 41 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 78 },
            { surahId: 24, surahName: 'An-Nur', verseId: 37 },
            { surahId: 24, surahName: 'An-Nur', verseId: 61 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 67 },
            { surahId: 27, surahName: 'An-Naml', verseId: 3 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 38 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 39 },
            { surahId: 31, surahName: 'Luqman', verseId: 4 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 35 },
            { surahId: 36, surahName: 'Ya-Sin', verseId: 47 },
            { surahId: 41, surahName: 'Fussilat', verseId: 7 },
            { surahId: 47, surahName: 'Muhammad', verseId: 36 },
            { surahId: 47, surahName: 'Muhammad', verseId: 37 },
            { surahId: 47, surahName: 'Muhammad', verseId: 38 },
            { surahId: 51, surahName: 'Adz-Dzariyat', verseId: 19 },
            { surahId: 52, surahName: 'Ath-Thur', verseId: 40 },
            { surahId: 57, surahName: 'Al-Hadid', verseId: 7 },
            { surahId: 57, surahName: 'Al-Hadid', verseId: 10 },
        ]
    },
    {
        id: 'akhlak',
        title: 'Akhlak Mulia',
        description: 'Panduan berakhlak mulia, kejujuran, menjauhi prasangka, dan menjaga lisan.',
        iconName: 'Smile',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 10 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 34 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 45 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 87 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 191 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 199 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 20 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 25 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 36 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 103 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 112 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 117 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 156 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 157 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 172 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 173 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 5 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 54 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 82 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 21 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 42 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 43 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 63 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 93 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 13 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 36 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 40 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 48 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 55 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 75 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 76 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 88 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 94 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 119 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 133 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 146 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 205 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 47 },
            { surahId: 10, surahName: 'Yunus', verseId: 12 },
            { surahId: 10, surahName: 'Yunus', verseId: 75 },
            { surahId: 11, surahName: 'Hud', verseId: 23 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 21 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 22 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 29 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 24 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 37 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 107 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 108 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 109 },
            { surahId: 19, surahName: 'Maryam', verseId: 20 },
            { surahId: 19, surahName: 'Maryam', verseId: 28 },
            { surahId: 19, surahName: 'Maryam', verseId: 32 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 108 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 111 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 134 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 19 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 90 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 91 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 8 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 9 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 34 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 35 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 54 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 1 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 2 },
        ]
    },
    {
        id: 'ibadah',
        title: 'Ibadah',
        description: 'Ketentuan dan keutamaan shalat, puasa, zakat, haji, dan dzikir.',
        iconName: 'BookOpen',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 3 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 45 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 110 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 129 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 157 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 183 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 187 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 197 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 200 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 239 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 286 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 16 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 97 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 183 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 43 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 101 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 142 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 1 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 12 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 58 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 94 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 97 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 92 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 12 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 120 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 206 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 5 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 54 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 99 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 108 },
            { surahId: 10, surahName: 'Yunus', verseId: 87 },
            { surahId: 12, surahName: 'Yusuf', verseId: 4 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 15 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 35 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 38 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 41 },
            { surahId: 15, surahName: 'Al-Hijr', verseId: 31 },
            { surahId: 15, surahName: 'Al-Hijr', verseId: 97 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 48 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 78 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 81 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 111 },
            { surahId: 19, surahName: 'Maryam', verseId: 8 },
            { surahId: 19, surahName: 'Maryam', verseId: 31 },
            { surahId: 19, surahName: 'Maryam', verseId: 59 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 35 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 130 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 18 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 28 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 31 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 34 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 41 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 2 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 118 },
            { surahId: 24, surahName: 'An-Nur', verseId: 41 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 60 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 83 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 118 },
            { surahId: 27, surahName: 'An-Naml', verseId: 24 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 17 },
            { surahId: 31, surahName: 'Luqman', verseId: 4 },
            { surahId: 32, surahName: 'As-Sajdah', verseId: 16 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 43 },
            { surahId: 35, surahName: 'Fatir', verseId: 29 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 102 },
        ]
    },
    {
        id: 'ilmu',
        title: 'Ilmu Pengetahuan',
        description: 'Perintah menuntut ilmu, tadabbur ayat-ayat Allah, dan derajat orang berilmu.',
        iconName: 'Lightbulb',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 32 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 129 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 209 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 231 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 251 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 269 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 44 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 58 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 81 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 137 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 190 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 17 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 26 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 56 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 92 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 111 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 130 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 165 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 38 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 118 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 73 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 99 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 139 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 10 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 63 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 71 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 28 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 60 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 97 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 110 },
            { surahId: 10, surahName: 'Yunus', verseId: 5 },
            { surahId: 11, surahName: 'Hud', verseId: 1 },
            { surahId: 12, surahName: 'Yusuf', verseId: 83 },
            { surahId: 12, surahName: 'Yusuf', verseId: 110 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 3 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 4 },
            { surahId: 15, surahName: 'Al-Hijr', verseId: 25 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 11 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 13 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 15 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 60 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 39 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 121 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 68 },
            { surahId: 24, surahName: 'An-Nur', verseId: 18 },
            { surahId: 27, surahName: 'An-Naml', verseId: 6 },
            { surahId: 29, surahName: 'Al-\'Ankabut', verseId: 20 },
            { surahId: 29, surahName: 'Al-\'Ankabut', verseId: 42 },
            { surahId: 31, surahName: 'Luqman', verseId: 2 },
            { surahId: 31, surahName: 'Luqman', verseId: 9 },
            { surahId: 31, surahName: 'Luqman', verseId: 27 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 34 },
            { surahId: 34, surahName: 'Saba\'', verseId: 27 },
            { surahId: 36, surahName: 'Ya-Sin', verseId: 2 },
            { surahId: 38, surahName: 'Sad', verseId: 29 },
            { surahId: 40, surahName: 'Ghafir', verseId: 8 },
            { surahId: 42, surahName: 'Asy-Syura', verseId: 3 },
            { surahId: 43, surahName: 'Az-Zukhruf', verseId: 4 },
            { surahId: 43, surahName: 'Az-Zukhruf', verseId: 84 },
            { surahId: 45, surahName: 'Al-Jatsiyah', verseId: 2 },
            { surahId: 46, surahName: 'Al-Ahqaf', verseId: 2 },
            { surahId: 48, surahName: 'Al-Fath', verseId: 4 },
            { surahId: 48, surahName: 'Al-Fath', verseId: 19 },
            { surahId: 51, surahName: 'Adz-Dzariyat', verseId: 30 },
            { surahId: 54, surahName: 'Al-Qamar', verseId: 5 },
        ]
    },
    {
        id: 'tauhid',
        title: 'Tauhid & Kebesaran Allah',
        description: 'Mengenal keesaan Allah, asmaul husna, dan tanda-tanda kebesaran-Nya.',
        iconName: 'Shield',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 163 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 255 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 2 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 6 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 18 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 133 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 134 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 135 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 136 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 87 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 73 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 102 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 106 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 54 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 158 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 31 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 129 },
            { surahId: 10, surahName: 'Yunus', verseId: 3 },
            { surahId: 10, surahName: 'Yunus', verseId: 90 },
            { surahId: 11, surahName: 'Hud', verseId: 7 },
            { surahId: 11, surahName: 'Hud', verseId: 14 },
            { surahId: 11, surahName: 'Hud', verseId: 50 },
            { surahId: 11, surahName: 'Hud', verseId: 61 },
            { surahId: 11, surahName: 'Hud', verseId: 84 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 2 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 30 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 2 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 42 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 5 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 8 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 14 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 98 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 22 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 25 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 87 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 23 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 32 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 86 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 91 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 116 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 59 },
            { surahId: 27, surahName: 'An-Naml', verseId: 26 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 70 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 88 },
            { surahId: 32, surahName: 'As-Sajdah', verseId: 4 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 42 },
            { surahId: 35, surahName: 'Fatir', verseId: 3 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 4 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 5 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 35 },
            { surahId: 38, surahName: 'Sad', verseId: 65 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 6 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 75 },
            { surahId: 40, surahName: 'Ghafir', verseId: 3 },
            { surahId: 40, surahName: 'Ghafir', verseId: 7 },
            { surahId: 40, surahName: 'Ghafir', verseId: 15 },
            { surahId: 40, surahName: 'Ghafir', verseId: 62 },
            { surahId: 40, surahName: 'Ghafir', verseId: 65 },
            { surahId: 43, surahName: 'Az-Zukhruf', verseId: 82 },
            { surahId: 43, surahName: 'Az-Zukhruf', verseId: 84 },
            { surahId: 44, surahName: 'Ad-Dukhan', verseId: 8 },
            { surahId: 47, surahName: 'Muhammad', verseId: 19 },
            { surahId: 57, surahName: 'Al-Hadid', verseId: 4 },
            { surahId: 59, surahName: 'Al-Hasyr', verseId: 22 },
            { surahId: 59, surahName: 'Al-Hasyr', verseId: 23 },
        ]
    },
    {
        id: 'hari_akhir',
        title: 'Hari Akhir & Kiamat',
        description: 'Gambaran hari kiamat, hisab, surga, dan neraka sebagai pengingat jiwa.',
        iconName: 'Hourglass',
        references: [
            { surahId: 1, surahName: 'Al-Fatihah', verseId: 4 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 82 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 130 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 212 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 265 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 114 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 161 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 197 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 57 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 115 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 159 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 37 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 119 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 141 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 38 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 49 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 16 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 21 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 68 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 100 },
            { surahId: 10, surahName: 'Yunus', verseId: 27 },
            { surahId: 11, surahName: 'Hud', verseId: 60 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 4 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 23 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 29 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 8 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 52 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 98 },
            { surahId: 18, surahName: 'Al-Kahf', verseId: 39 },
            { surahId: 18, surahName: 'Al-Kahf', verseId: 106 },
            { surahId: 19, surahName: 'Maryam', verseId: 70 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 101 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 47 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 19 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 66 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 103 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 12 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 69 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 134 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 72 },
            { surahId: 29, surahName: 'Al-\'Ankabut', verseId: 54 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 56 },
            { surahId: 32, surahName: 'As-Sajdah', verseId: 20 },
            { surahId: 34, surahName: 'Saba\'', verseId: 12 },
            { surahId: 35, surahName: 'Fatir', verseId: 33 },
            { surahId: 36, surahName: 'Ya-Sin', verseId: 63 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 63 },
            { surahId: 38, surahName: 'Sad', verseId: 50 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 8 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 47 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 75 },
            { surahId: 40, surahName: 'Ghafir', verseId: 46 },
            { surahId: 41, surahName: 'Fussilat', verseId: 24 },
            { surahId: 42, surahName: 'Asy-Syura', verseId: 7 },
            { surahId: 43, surahName: 'Az-Zukhruf', verseId: 72 },
            { surahId: 45, surahName: 'Al-Jatsiyah', verseId: 10 },
            { surahId: 46, surahName: 'Al-Ahqaf', verseId: 16 },
            { surahId: 48, surahName: 'Al-Fath', verseId: 5 },
            { surahId: 50, surahName: 'Qaf', verseId: 31 },
            { surahId: 52, surahName: 'Ath-Thur', verseId: 16 },
            { surahId: 54, surahName: 'Al-Qamar', verseId: 48 },
            { surahId: 56, surahName: 'Al-Waqi\'ah', verseId: 52 },
            { surahId: 57, surahName: 'Al-Hadid', verseId: 21 },
            { surahId: 58, surahName: 'Al-Mujadilah', verseId: 22 },
            { surahId: 63, surahName: 'Al-Munafiqun', verseId: 2 },
            { surahId: 66, surahName: 'At-Tahrim', verseId: 8 },
            { surahId: 67, surahName: 'Al-Mulk', verseId: 8 },
            { surahId: 69, surahName: 'Al-Haqqah', verseId: 31 },
            { surahId: 71, surahName: 'Nuh', verseId: 25 },
            { surahId: 74, surahName: 'Al-Muddatstsir', verseId: 28 },
        ]
    },
    {
        id: 'taubat',
        title: 'Taubat & Ampunan',
        description: 'Pintu taubat yang luas, ampunan Allah, dan cara menghapus dosa.',
        iconName: 'RefreshCw',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 37 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 54 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 128 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 159 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 160 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 187 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 222 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 278 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 279 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 89 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 90 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 128 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 15 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 16 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 17 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 18 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 27 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 64 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 92 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 145 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 146 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 33 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 34 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 39 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 71 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 74 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 54 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 143 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 153 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 3 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 5 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 11 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 15 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 27 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 74 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 102 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 104 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 106 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 112 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 117 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 118 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 126 },
            { surahId: 11, surahName: 'Hud', verseId: 3 },
            { surahId: 11, surahName: 'Hud', verseId: 52 },
            { surahId: 11, surahName: 'Hud', verseId: 61 },
            { surahId: 11, surahName: 'Hud', verseId: 90 },
            { surahId: 11, surahName: 'Hud', verseId: 112 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 6 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 30 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 119 },
            { surahId: 19, surahName: 'Maryam', verseId: 59 },
            { surahId: 19, surahName: 'Maryam', verseId: 60 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 82 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 122 },
            { surahId: 24, surahName: 'An-Nur', verseId: 4 },
            { surahId: 24, surahName: 'An-Nur', verseId: 5 },
            { surahId: 24, surahName: 'An-Nur', verseId: 10 },
            { surahId: 24, surahName: 'An-Nur', verseId: 31 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 69 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 70 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 71 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 67 },
            { surahId: 31, surahName: 'Luqman', verseId: 15 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 73 },
            { surahId: 40, surahName: 'Ghafir', verseId: 3 },
        ]
    },
    {
        id: 'syukur',
        title: 'Syukur & Nikmat',
        description: 'Mensyukuri nikmat Allah dan balasan bagi orang-orang yang bersyukur.',
        iconName: 'Heart',
        references: [
            { surahId: 1, surahName: 'Al-Fatihah', verseId: 5 },
            { surahId: 1, surahName: 'Al-Fatihah', verseId: 6 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 40 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 47 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 122 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 150 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 211 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 231 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 103 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 171 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 174 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 69 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 72 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 3 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 6 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 7 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 11 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 20 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 23 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 110 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 118 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 138 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 69 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 74 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 137 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 53 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 69 },
            { surahId: 11, surahName: 'Hud', verseId: 10 },
            { surahId: 11, surahName: 'Hud', verseId: 48 },
            { surahId: 11, surahName: 'Hud', verseId: 73 },
            { surahId: 12, surahName: 'Yusuf', verseId: 6 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 6 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 28 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 34 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 18 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 53 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 71 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 72 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 81 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 83 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 112 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 114 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 121 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 1 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 83 },
            { surahId: 19, surahName: 'Maryam', verseId: 58 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 71 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 81 },
            { surahId: 27, surahName: 'An-Naml', verseId: 19 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 17 },
            { surahId: 29, surahName: 'Al-\'Ankabut', verseId: 67 },
            { surahId: 31, surahName: 'Luqman', verseId: 20 },
            { surahId: 31, surahName: 'Luqman', verseId: 31 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 9 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 37 },
            { surahId: 34, surahName: 'Saba\'', verseId: 18 },
            { surahId: 35, surahName: 'Fatir', verseId: 3 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 55 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 56 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 57 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 113 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 8 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 49 },
            { surahId: 41, surahName: 'Fussilat', verseId: 10 },
            { surahId: 41, surahName: 'Fussilat', verseId: 51 },
        ]
    },
    {
        id: 'kisah_nabi',
        title: 'Kisah Para Nabi',
        description: 'Kisah perjuangan, keteladanan, dan mukjizat para Nabi dan Rasul.',
        iconName: 'Compass',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 30 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 67 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 131 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 33 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 84 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 164 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 110 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 80 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 20 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 62 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 111 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 124 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 137 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 150 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 163 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 43 },
            { surahId: 10, surahName: 'Yunus', verseId: 73 },
            { surahId: 10, surahName: 'Yunus', verseId: 87 },
            { surahId: 11, surahName: 'Hud', verseId: 29 },
            { surahId: 11, surahName: 'Hud', verseId: 44 },
            { surahId: 11, surahName: 'Hud', verseId: 89 },
            { surahId: 12, surahName: 'Yusuf', verseId: 14 },
            { surahId: 12, surahName: 'Yusuf', verseId: 27 },
            { surahId: 12, surahName: 'Yusuf', verseId: 40 },
            { surahId: 12, surahName: 'Yusuf', verseId: 53 },
            { surahId: 12, surahName: 'Yusuf', verseId: 66 },
            { surahId: 12, surahName: 'Yusuf', verseId: 79 },
            { surahId: 12, surahName: 'Yusuf', verseId: 92 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 8 },
            { surahId: 15, surahName: 'Al-Hijr', verseId: 55 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 104 },
            { surahId: 18, surahName: 'Al-Kahf', verseId: 71 },
            { surahId: 19, surahName: 'Maryam', verseId: 22 },
            { surahId: 19, surahName: 'Maryam', verseId: 47 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 13 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 26 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 39 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 52 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 65 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 78 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 91 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 120 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 59 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 72 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 26 },
            { surahId: 23, surahName: 'Al-Mu\'minun', verseId: 46 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 14 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 27 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 40 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 53 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 66 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 109 },
            { surahId: 27, surahName: 'An-Naml', verseId: 7 },
            { surahId: 27, surahName: 'An-Naml', verseId: 20 },
            { surahId: 27, surahName: 'An-Naml', verseId: 33 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 4 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 17 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 30 },
            { surahId: 28, surahName: 'Al-Qasas', verseId: 43 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 37 },
            { surahId: 36, surahName: 'Ya-Sin', verseId: 60 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 90 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 103 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 118 },
            { surahId: 38, surahName: 'Sad', verseId: 12 },
            { surahId: 38, surahName: 'Sad', verseId: 43 },
            { surahId: 40, surahName: 'Ghafir', verseId: 53 },
            { surahId: 43, surahName: 'Az-Zukhruf', verseId: 53 },
            { surahId: 44, surahName: 'Ad-Dukhan', verseId: 24 },
            { surahId: 44, surahName: 'Ad-Dukhan', verseId: 37 },
        ]
    },
    {
        id: 'keadilan',
        title: 'Keadilan & Kejujuran',
        description: 'Kewajiban berbuat adil, bersaksi dengan benar, dan menjauhi kezaliman.',
        iconName: 'Scale',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 180 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 281 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 282 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 283 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 18 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 21 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 3 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 58 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 105 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 106 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 107 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 108 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 109 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 110 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 111 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 112 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 127 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 129 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 135 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 8 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 42 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 95 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 106 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 115 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 152 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 29 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 159 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 181 },
            { surahId: 10, surahName: 'Yunus', verseId: 4 },
            { surahId: 10, surahName: 'Yunus', verseId: 47 },
            { surahId: 10, surahName: 'Yunus', verseId: 54 },
            { surahId: 11, surahName: 'Hud', verseId: 85 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 76 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 35 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 4 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 72 },
            { surahId: 33, surahName: 'Al-Ahzab', verseId: 5 },
            { surahId: 40, surahName: 'Ghafir', verseId: 17 },
            { surahId: 40, surahName: 'Ghafir', verseId: 30 },
            { surahId: 40, surahName: 'Ghafir', verseId: 31 },
            { surahId: 42, surahName: 'Asy-Syura', verseId: 15 },
            { surahId: 49, surahName: 'Al-Hujurat', verseId: 9 },
            { surahId: 55, surahName: 'Ar-Rahman', verseId: 9 },
            { surahId: 57, surahName: 'Al-Hadid', verseId: 25 },
            { surahId: 60, surahName: 'Al-Mumtahanah', verseId: 8 },
            { surahId: 95, surahName: 'At-Tin', verseId: 8 },
        ]
    },
    {
        id: 'alam',
        title: 'Alam Semesta & Penciptaan',
        description: 'Penciptaan langit, bumi, bintang, gunung, dan fenomena alam.',
        iconName: 'Globe',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 11 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 50 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 117 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 255 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 5 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 156 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 101 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 17 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 97 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 12 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 79 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 19 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 57 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 160 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 63 },
            { surahId: 10, surahName: 'Yunus', verseId: 18 },
            { surahId: 10, surahName: 'Yunus', verseId: 68 },
            { surahId: 11, surahName: 'Hud', verseId: 44 },
            { surahId: 12, surahName: 'Yusuf', verseId: 4 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 15 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 10 },
            { surahId: 14, surahName: 'Ibrahim', verseId: 46 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 3 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 59 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 55 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 93 },
            { surahId: 18, surahName: 'Al-Kahf', verseId: 40 },
            { surahId: 18, surahName: 'Al-Kahf', verseId: 84 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 6 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 130 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 79 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 21 },
            { surahId: 22, surahName: 'Al-Hajj', verseId: 78 },
            { surahId: 24, surahName: 'An-Nur', verseId: 39 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 6 },
            { surahId: 25, surahName: 'Al-Furqan', verseId: 62 },
            { surahId: 26, surahName: 'Asy-Syu\'ara\'', verseId: 149 },
            { surahId: 27, surahName: 'An-Naml', verseId: 58 },
            { surahId: 27, surahName: 'An-Naml', verseId: 82 },
            { surahId: 29, surahName: 'Al-\'Ankabut', verseId: 34 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 8 },
            { surahId: 30, surahName: 'Ar-Rum', verseId: 42 },
            { surahId: 31, surahName: 'Luqman', verseId: 25 },
            { surahId: 32, surahName: 'As-Sajdah', verseId: 27 },
            { surahId: 34, surahName: 'Saba\'', verseId: 16 },
            { surahId: 35, surahName: 'Fatir', verseId: 38 },
            { surahId: 36, surahName: 'Ya-Sin', verseId: 62 },
            { surahId: 37, surahName: 'As-Saffat', verseId: 64 },
            { surahId: 38, surahName: 'Sad', verseId: 18 },
            { surahId: 39, surahName: 'Az-Zumar', verseId: 21 },
            { surahId: 40, surahName: 'Ghafir', verseId: 21 },
            { surahId: 41, surahName: 'Fussilat', verseId: 10 },
            { surahId: 42, surahName: 'Asy-Syura', verseId: 12 },
            { surahId: 42, surahName: 'Asy-Syura', verseId: 53 },
            { surahId: 44, surahName: 'Ad-Dukhan', verseId: 24 },
            { surahId: 45, surahName: 'Al-Jatsiyah', verseId: 13 },
            { surahId: 46, surahName: 'Al-Ahqaf', verseId: 32 },
            { surahId: 49, surahName: 'Al-Hujurat', verseId: 16 },
            { surahId: 51, surahName: 'Adz-Dzariyat', verseId: 3 },
            { surahId: 52, surahName: 'Ath-Thur', verseId: 6 },
            { surahId: 53, surahName: 'An-Najm', verseId: 16 },
            { surahId: 54, surahName: 'Al-Qamar', verseId: 34 },
            { surahId: 55, surahName: 'Ar-Rahman', verseId: 37 },
            { surahId: 57, surahName: 'Al-Hadid', verseId: 1 },
            { surahId: 57, surahName: 'Al-Hadid', verseId: 22 },
            { surahId: 64, surahName: 'At-Taghabun', verseId: 1 },
            { surahId: 67, surahName: 'Al-Mulk', verseId: 24 },
            { surahId: 70, surahName: 'Al-Ma\'arij', verseId: 10 },
            { surahId: 71, surahName: 'Nuh', verseId: 26 },
            { surahId: 75, surahName: 'Al-Qiyamah', verseId: 9 },
        ]
    },
    {
        id: 'persaudaraan',
        title: 'Ukhuwah & Perdamaian',
        description: 'Menjalin persaudaraan sesama mukmin, mendamaikan pertikaian, dan kasih sayang.',
        iconName: 'Users',
        references: [
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 178 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 220 },
            { surahId: 2, surahName: 'Al-Baqarah', verseId: 228 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 103 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 156 },
            { surahId: 3, surahName: 'Ali \'Imran', verseId: 168 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 11 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 12 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 23 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 35 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 62 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 90 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 128 },
            { surahId: 4, surahName: 'An-Nisa\'', verseId: 176 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 25 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 30 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 31 },
            { surahId: 5, surahName: 'Al-Ma\'idah', verseId: 48 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 87 },
            { surahId: 6, surahName: 'Al-An\'am', verseId: 127 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 65 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 73 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 85 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 111 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 142 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 150 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 151 },
            { surahId: 7, surahName: 'Al-A\'raf', verseId: 202 },
            { surahId: 8, surahName: 'Al-Anfal', verseId: 61 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 11 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 23 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 24 },
            { surahId: 9, surahName: 'At-Tawbah', verseId: 60 },
            { surahId: 10, surahName: 'Yunus', verseId: 25 },
            { surahId: 10, surahName: 'Yunus', verseId: 87 },
            { surahId: 11, surahName: 'Hud', verseId: 50 },
            { surahId: 11, surahName: 'Hud', verseId: 61 },
            { surahId: 11, surahName: 'Hud', verseId: 84 },
            { surahId: 11, surahName: 'Hud', verseId: 118 },
            { surahId: 12, surahName: 'Yusuf', verseId: 5 },
            { surahId: 12, surahName: 'Yusuf', verseId: 7 },
            { surahId: 12, surahName: 'Yusuf', verseId: 8 },
            { surahId: 12, surahName: 'Yusuf', verseId: 58 },
            { surahId: 12, surahName: 'Yusuf', verseId: 59 },
            { surahId: 12, surahName: 'Yusuf', verseId: 63 },
            { surahId: 12, surahName: 'Yusuf', verseId: 64 },
            { surahId: 12, surahName: 'Yusuf', verseId: 65 },
            { surahId: 12, surahName: 'Yusuf', verseId: 69 },
            { surahId: 12, surahName: 'Yusuf', verseId: 70 },
            { surahId: 12, surahName: 'Yusuf', verseId: 76 },
            { surahId: 12, surahName: 'Yusuf', verseId: 77 },
            { surahId: 12, surahName: 'Yusuf', verseId: 87 },
            { surahId: 12, surahName: 'Yusuf', verseId: 89 },
            { surahId: 12, surahName: 'Yusuf', verseId: 90 },
            { surahId: 12, surahName: 'Yusuf', verseId: 100 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 23 },
            { surahId: 13, surahName: 'Ar-Ra\'d', verseId: 24 },
            { surahId: 15, surahName: 'Al-Hijr', verseId: 47 },
            { surahId: 16, surahName: 'An-Nahl', verseId: 93 },
            { surahId: 17, surahName: 'Al-Isra\'', verseId: 27 },
            { surahId: 19, surahName: 'Maryam', verseId: 53 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 29 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 30 },
            { surahId: 20, surahName: 'Ta-Ha', verseId: 42 },
            { surahId: 21, surahName: 'Al-Anbiya\'', verseId: 92 },
        ]
    },
];
